Repository Automattic/mongoose, pull requests merged in 2018-04, with the labels that each got.

#6309 adding middleware to faq arrow function warning
  docs/faq.jade
Labels: docs

#6287 WIP: Map type
  lib/document.js
  lib/schema.js
  lib/schema/embedded.js
  lib/schema/map.js
  lib/types/map.js
  lib/types/subdocument.js
  test/types.map.test.js
Labels: discussion, new feature

#6365 Docs: Update schematypes.jade
  docs/schematypes.jade
Labels: docs

#6367 Removing mention of "numAffected" from document.save example
  lib/document.js
Labels: docs

#6370 Change docs for create collection
  lib/connection.js
Labels: docs

#6353 adding aggregation/query cursor to api docs #6344
  docs/layout.jade
  docs/source/api.js
Labels: docs

#6374 sort api methods based on their string property
  docs/source/api.js
Labels: docs

#6363 Session support for docs
  .travis.yml
  lib/document.js
  lib/drivers/node-mongodb-native/collection.js
  lib/internal.js
  lib/model.js
  lib/query.js
  lib/services/query/completeMany.js
  test/model.test.js
Labels: new feature

#6401 docs(migration): certain in passwords may cause connection failures
  migrating_to_5.md
Labels: docs
