Repository Automattic/mongoose, pull requests merged in 2020-12, with the labels that each got.

#9652 fix(index.d.ts): add `Document#__v` so documents have a Version by default
  index.d.ts
  test/typescript/createBasicSchemaDefinition.ts
Labels: typescript

#9655 fix(index.d.ts): add the missing generic declaration for Schema
  index.d.ts
Labels: typescript

#9663 fix(index.d.ts): Change options in Connection#collection() to be optional
  index.d.ts
  test/typescript/connection.ts
Labels: typescript

#9661 types(base): add mongoose.models re #9660
  index.d.ts
  test/typescript/base.ts
  test/typescript/main.test.js
  test/typescript/ts.config.json
Labels: typescript

#9665 fix(index.ts): allow the next() argument to be optional
  index.d.ts
Labels: typescript

#9680 fix(index.d.ts): Fix return type of Model#aggregate()
  index.d.ts
  test/typescript/models.ts
Labels: typescript

#9683 optional next() parameter for post middleware
  index.d.ts
Labels: typescript

#9685 fix(index.d.ts): allow 2 generic types in mongoose.model function
  index.d.ts
Labels: typescript

#9686 Allow array of validators in SchemaTypeOptions
  index.d.ts
Labels: typescript

#9692 fix(index.d.ts): add missing Aggregate#skip() & Aggregate#limit()
  index.d.ts
Labels: typescript

#9696 fix(index.d.ts): add missing single document populate
  index.d.ts
Labels: typescript

#9700 fix(index.d.ts): make options optional for `toObject`
  index.d.ts
Labels: typescript

#9701 enhancement(schemaType): pass document to default functions
  lib/schematype.js
  test/document.test.js
Labels: backwards-breaking

#9705 fix(css): media query for ::before on headings
  docs/css/mongoose5.css
Labels: docs

#9710 added missing match and model methods in Aggregate class in type defi…
  index.d.ts
Labels: docs

#9743 fix(index.d.ts): add missing pre hook for findOneAndUpdate
  index.d.ts
Labels: typescript

#9744 fix(index.d.ts): add missing overloaded function for Document#populate()
  index.d.ts
Labels: typescript
