Repository Automattic/mongoose, pull requests merged in 2020-04, with the labels that each got.

#8779 docs(guide): fix English
  docs/3.3.x/docs/guide.jade
Labels: docs

#8780 docs(guide): fix English
  docs/guide.pug
Labels: docs

#8788 docs(lib/model): fix punctuation
  lib/model.js
Labels: docs

#8791 docs: add skipId to model
  lib/model.js
Labels: docs

#8793 docs(queries): rm extra word
  docs/queries.pug
Labels: docs

#8794 docs(populate): typo fix
  docs/populate.pug
Labels: docs

#8799 Fix for updatedAt on sub-sub-documents
  lib/helpers/update/applyTimestampsToChildren.js
  test/timestamps.test.js
Labels: confirmed-bug

#8820 docs(api): detail what the insertMany Promise resolves to
  lib/model.js
Labels: docs

#8817 Make Model.create() return an empty array when passed an empty array
  lib/model.js
  test/model.create.test.js
Labels: backwards-breaking

#8825 Docs: make questions on FAQ anchorable
  docs/faq.pug
Labels: docs

#8823 [WIP] refactor: use (for-of) instead of for (let i = 0...) when iterating on arrays
  lib/aggregate.js
  lib/cast.js
  lib/collection.js
  lib/connection.js
  lib/document.js
  lib/error/validator.js
  lib/helpers/clone.js
  lib/helpers/model/applyHooks.js
  lib/helpers/model/discriminator.js
  lib/helpers/populate/getModelsMapForPopulate.js
  lib/helpers/populate/getSchemaTypes.js
  lib/helpers/query/selectPopulatedFields.js
  lib/helpers/schema/applyPlugins.js
  lib/helpers/schema/getIndexes.js
  lib/helpers/updateValidators.js
  lib/model.js
  lib/query.js
  lib/queryhelpers.js
  lib/schema.js
  lib/schema/array.js
  lib/schema/string.js
  lib/schematype.js
  lib/types/core_array.js
  lib/types/documentarray.js
  lib/types/map.js
  lib/utils.js
  test/document.test.js
  test/model.geosearch.test.js
  test/types.number.test.js
  website.js
Labels: refactor
