Repository Automattic/mongoose, pull requests merged in 2021-07, with the labels that each got.

#10395 fix(index.d.ts): proper placement of `mongoose.Date` JSDoc
  index.d.ts
Labels: developer-experience

#10393 Replace mongodb-topology-manager
  package.json
  test/common.js
  test/connection.test.js
  test/connection_server.js
Labels: refactor

#10494 Make LeanDocument work with PopulatedDoc
  index.d.ts
  test/typescript/main.test.js
  test/typescript/populate.ts
Labels: typescript

#10501 Update depopulate documentation for document.js
  lib/document.js
Labels: docs
