Repository Automattic/mongoose, pull requests merged in 2022-07, with the labels that each got.

#12076 Add `String[]` as type in jsdoc for `Schema.prototype.pre/post`
  lib/schema.js
Labels: docs

#12101 Solves `syncIndexes` type error on `continueOn Error` option
  types/indexes.d.ts
Labels: typescript

#12103 chore: upgrade mongodb driver to 4.8.0
  package.json
Labels: dependencies

#12088 fix(types): fix $switch expression type
  test/types/expressions.test.ts
  types/expressions.d.ts
Labels: typescript

#12087 fix(types): add $let as a possible expression to $addFields
  test/types/PipelineStage.test.ts
  types/expressions.d.ts
Labels: typescript

#12082 feat(model): allow passing `timestamps` option to `Model.bulkSave(...)`
  lib/helpers/model/castBulkWrite.js
  lib/model.js
  lib/utils.js
  test/model.test.js
  test/types/models.test.ts
  types/models.d.ts
Labels: new feature

#12057 feat(model): add `applyDefaults()` helper that allows applying defaults to document or POJO
  lib/document.js
  lib/helpers/document/applyDefaults.js
  lib/helpers/model/applyDefaultsToPOJO.js
  lib/helpers/timestamps/setDocumentTimestamps.js
  lib/helpers/timestamps/setupTimestamps.js
  lib/helpers/topology/isAtlas.js
  lib/index.js
  lib/model.js
  lib/schema/documentarray.js
  lib/schematype.js
  test/model.test.js
  test/types/PipelineStage.test.ts
  test/types/expressions.test.ts
  test/types/models.test.ts
  test/types/queries.test.ts
  types/expressions.d.ts
  types/index.d.ts
Labels: new feature
