Repository Automattic/mongoose, pull requests merged in 2022-11, with the labels that each got.

#12609 docs: add Lodash guide highlighting issues with cloneDeep()
  docs/guides.md
  docs/lodash.md
  docs/source/index.js
Labels: docs

#12641 Removed v5 link from v6 docs
  docs/connections.md
Labels: docs

#12646 chore(workflows): update actions/checkout to 3.1.0
  .github/workflows/benchmark.yml
  .github/workflows/codeql.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  .github/workflows/tidelift-alignment.yml
  .github/workflows/tsd.yml
Labels: github_actions

#12649 fix(types): make array paths optional in inferred type of array default returns undefined
  test/types/schema.test.ts
  types/inferschematype.d.ts
Labels: typescript

#12642 fix(type): pre hook with deleteOne should resolve this as Query
  test/types/models.test.ts
  types/index.d.ts
Labels: typescript

#12650 fix(types): add UUID to types
  test/types/schema.test.ts
  types/inferschematype.d.ts
  types/schematypes.d.ts
Labels: typescript

#12659 fix(types): correct handling for model<any>
  test/types/models.test.ts
  types/index.d.ts
  types/inferschematype.d.ts
  types/utility.d.ts
Labels: typescript

#12663 fix(types): set `this` to doc type in `SchemaType.prototype.validate()`
  test/types/schema.test.ts
  types/index.d.ts
  types/schematypes.d.ts
Labels: typescript

#12623 fix(docs): links starting with "/docs/" on markdown doc files are relative links
  docs/change-streams.md
  docs/connections.md
  docs/deprecations.md
  docs/documents.md
  docs/faq.md
  docs/geojson.md
  docs/guide.md
  docs/guides.md
  docs/index.md
  docs/middleware.md
  docs/migrating_to_5.md
  docs/migrating_to_6.md
  docs/models.md
  docs/plugins.md
  docs/populate.md
  docs/queries.md
  docs/schematypes.md
  docs/transactions.md
  docs/tutorials/dates.md
  docs/tutorials/findoneandupdate.md
  docs/tutorials/getters-setters.md
  docs/tutorials/lean.md
  docs/tutorials/ssl.md
  docs/tutorials/virtuals.md
  docs/typescript.md
  docs/typescript/schemas.md
  docs/typescript/statics-and-methods.md
  docs/typescript/statics.md
  docs/typescript/virtuals.md
  docs/validation.md
Labels: docs

#12690 [DOCS] Update remaining relative and static links, also add style guidelines for documentation
  CONTRIBUTING.md
  docs/async-await.md
  docs/connections.md
  docs/documents.md
  docs/faq.md
  docs/guide.md
  docs/jest.md
  docs/lodash.md
  docs/middleware.md
  docs/models.md
  docs/populate.md
  docs/promises.md
  docs/queries.md
  docs/schematypes.md
  docs/subdocs.md
  docs/tutorials/custom-casting.md
  docs/tutorials/getters-setters.md
  docs/tutorials/query_casting.md
  docs/validation.md
Labels: docs

#12712 fix(types): avoid typeof Query with generics for TypeScript 4.6 support
  types/query.d.ts
Labels: typescript

#12727 fix(types): infer virtuals in query results
  test/types/virtuals.test.ts
  types/index.d.ts
Labels: typescript
