Repository Automattic/mongoose, pull requests merged in 2022-06, with the labels that each got.

#11922 fix: toJSON with undefined path, add unit test
  lib/document.js
  test/document.test.js
Labels: confirmed-bug

#11965 [Types] Re-add the possibility to pass undefined for projection in Model.find
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript

#11982 docs: Update validation.md
  docs/validation.md
Labels: docs

#11997 fix(types): change index "weights" to be more explicit
  types/indexes.d.ts
Labels: typescript
