Repository Automattic/mongoose, pull requests merged in 2023-09, with the labels that each got.

#13818 fix: remove duplicated 'exists' method in Model interface in models.d.ts
  types/models.d.ts
Labels: typescript

#13850 docs(model): add examples of using `diffIndexes()` to `syncIndexes()`and `diffIndexes()` api docs
  lib/model.js
  test/types/schema.test.ts
Labels: docs

#13884 docs(deprecations): fix typo in includeResultMetadata deprecation docs
  docs/deprecations.md
Labels: docs

#13865 chore(docs/source/api): fix filenames
  docs/source/api.js
Labels: docs

#13843 BREAKING CHANGE: apply minimize by default when updating document
  lib/document.js
  lib/helpers/minimize.js
  lib/model.js
  test/document.test.js
Labels: backwards-breaking
