Repository Automattic/mongoose, pull requests merged in 2023-10, with the labels that each got.

#13910 docs(migrating_to_8): fix no ending-new-line (lint)
  docs/migrating_to_8.md
Labels: docs

#13905 Allow importing Mongoose without any MongoDB specifics, take 2
  lib/index.js
  lib/mongoose.js
  lib/query.js
Labels: backwards-breaking

#13946 chore(npmignore): ignore newer files
  .npmignore
Labels: developer-experience

#13947 chore: bump bson to match mongodb@5.9.0 exactly
  package.json
Labels: dependencies

#13964 types(models): add cleaner type definitions for `insertMany()` with no generics to prevent errors when using `insertMany()` in generic classes
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript

#13965 types(model): make InsertManyResult consistent with return type of insertMany
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript

#13990 types(models): make all properties to Model constructor optional
  docs/migrating_to_8.md
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript

#14004 chore(scripts/website): fix script to correctly parse "-rc" like versions
  scripts/website.js
Labels: docs

#14021 docs(migrating_to_7): add note about requiring `new` with `ObjectId`
  docs/migrating_to_7.md
Labels: docs
