Repository Automattic/mongoose, pull requests merged in 2023-07, with the labels that each got.

#13593 docs(guide): fix md lint
  docs/guide.md
Labels: docs

#13544 feat(model): add create option "immediateError"
  lib/model.js
  test/model.create.test.js
  test/types/create.test.ts
  types/models.d.ts
Labels: enhancement

#13635 docs: rework several code examples that still use callbacks
  docs/async-await.md
  docs/faq.md
  docs/middleware.md
  docs/queries.md
  lib/model.js
  test/model.insertMany.test.js
Labels: docs

#13632 types: correctly handle `pre('deleteOne', { document: true })`
  test/types/middleware.test.ts
  types/index.d.ts
Labels: typescript

#13628 types(schema): handle `type: Schema.Types.Map` in TypeScript
  test/types/schema.test.ts
  types/inferschematype.d.ts
Labels: typescript

#13641 feat: change all symbols to use a consistent name
  lib/helpers/populate/assignRawDocsToIdStructure.js
  lib/helpers/promiseOrCallback.js
  lib/helpers/symbols.js
Labels: developer-experience
