Repository Automattic/mongoose, pull requests merged in 2023-11, with the labels that each got.

#14095 types: allow defining document array using `[{ prop: String }]` syntax
  test/types/docArray.test.ts
  test/types/schema.test.ts
  types/inferschematype.d.ts
Labels: typescript

#14110 types(document): correct return type for `doc.deleteOne()` re: Mongoose 8 breaking change
  test/types/document.test.ts
  types/document.d.ts
Labels: typescript

#14112 types(models): allow specifying `timestamps` as inline option for bulkWrite() operations
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript

#14118 types(query): base filters and projections off of RawDocType instead of DocType so autocomplete doesn't show populate
  types/query.d.ts
Labels: typescript

#14123 types: make property names show up in intellisense for UpdateQuery
  types/index.d.ts
Labels: developer-experience, typescript

#14126 docs(README): update breaking change version
  README.md
Labels: docs

#14125 docs(source/api): fix "index.js" -> "mongoose.js" rename
  docs/source/api.js
Labels: docs
