Repository Automattic/mongoose, pull requests merged in 2024-12, with the labels that each got.

#15059 feat: allow specifying error message override for duplicate key errors `unique: true`
  lib/helpers/schema/getIndexes.js
  lib/model.js
  lib/query.js
  lib/schema.js
  lib/schemaType.js
  test/document.test.js
  test/types/schema.test.ts
  types/index.d.ts
  types/indexes.d.ts
  types/schematypes.d.ts
Labels: enhancement

#15085 types: add splice() to DocumentArray to allow adding partial objects with splice()
  test/types/docArray.test.ts
  types/types.d.ts
Labels: typescript

#15095 Remove more `callback` doc references & some small other changes
  index.js
  lib/connection.js
  lib/cursor/aggregationCursor.js
  lib/document.js
  lib/drivers/node-mongodb-native/collection.js
  lib/model.js
  lib/mongoose.js
  lib/query.js
  lib/schema/string.js
  package.json
Labels: docs, developer-experience

#15097 types(document): make sure `toObject()` and `toJSON()` apply versionKey __v
  test/types/document.test.ts
  types/document.d.ts
Labels: typescript

#15113 docs(connection+document+model): remove remaining references to remove(), clarify that deleteOne() does not execute until then() or exec()
  lib/connection.js
  lib/document.js
  lib/model.js
Labels: docs

#15103 types: correctly handle union types in BufferToBinary and related helpers
  test/types/lean.test.ts
  types/index.d.ts
Labels: typescript

#15115 types: add UUID to RefType
  docs/typescript/populate.md
  types/index.d.ts
Labels: typescript

#15119 move search endpoint to netlify
  docs/js/search.js
Labels: docs

#15123 types: make BufferToBinary avoid Document instances
  test/types/lean.test.ts
  types/index.d.ts
Labels: typescript

#15127 types: add cleanIndexes() to IndexManager interface
  lib/model.js
  types/indexes.d.ts
Labels: typescript

#15134 types(schema): add missing removeIndex
  types/index.d.ts
Labels: typescript

#15132 types(model+query): avoid stripping out virtuals when calling populate with paths generic
  test/types/populate.test.ts
  types/models.d.ts
  types/query.d.ts
Labels: typescript
