Repository Automattic/mongoose, pull requests merged in 2024-05, with the labels that each got.

#14564 docs(connections): improve description of connection creation patterns
  docs/connections.md
Labels: docs

#14565 perf(document): avoid cloning options using spread operator for perf reasons
  lib/document.js
  test/document.test.js
  test/model.populate.test.js
Labels: performance

#14571 types(model): allow passing strict type checking override to create()
  test/types/create.test.ts
  types/models.d.ts
Labels: typescript

#14575 docs(typescript): clarify that setting THydratedDocumentType on schemas is necessary for correct method context
  docs/typescript/schemas.md
  test/types/schema.test.ts
Labels: docs, typescript

#14581 types(model+query): pass TInstanceMethods to QueryWithHelpers so populated docs have methods
  test/types/populate.test.ts
  types/models.d.ts
  types/query.d.ts
Labels: typescript

#14583 feat: add `transactionAsyncLocalStorage` option to opt in to automatically setting `session` on all transactions
  docs/transactions.md
  lib/aggregate.js
  lib/connection.js
  lib/model.js
  lib/mongoose.js
  lib/query.js
  lib/validOptions.js
  test/docs/transactions.test.js
  test/model.findByIdAndUpdate.test.js
  types/mongooseoptions.d.ts
Labels: new feature

#13764 upgrade to mongodb-memory-server 9.0.0
  .github/workflows/test.yml
  package.json
  test/schema.select.test.js
Labels: dependencies

#14612 types: pass DocType down to subdocuments so `HydratedSingleSubdocument` and `HydratedArraySubdocument` `toObject()` returns correct type
  test/types/subdocuments.test.ts
  types/index.d.ts
  types/types.d.ts
Labels: typescript
