Repository Automattic/mongoose, pull requests merged in 2024-04, with the labels that each got.

#14499 types(validation): support function for validator `message` property, and add support for accessing validator `reason`
  test/types/schema.test.ts
  types/schematypes.d.ts
  types/validation.d.ts
Labels: typescript

#14509 style(model): fix typo in "$__updateConnection" docs
  lib/model.js
Labels: docs

#14501 chore: remove typo
  docs/connections.md
Labels: docs

#14514 Add documentation for calling `schema.post()` with async function
  docs/middleware.md
  test/types/middleware.test.ts
Labels: docs

#14526 types(DocumentArray): pass DocType generic to Document for correct toJSON() and toObject() return types
  test/types/docArray.test.ts
  types/types.d.ts
Labels: typescript

#14525 types(query+populate): apply populate overrides to doc `toObject()` result
  test/types/populate.test.ts
  test/types/queries.test.ts
  types/query.d.ts
Labels: typescript

#14541 types(document): make document _id type default to unknown instead of any
  lib/schema/documentArray.js
  test/model.test.js
  types/document.d.ts
  types/types.d.ts
Labels: typescript

#14534 types(schema): correctly infer Array<Schema.Types.*>
  test/types/schema.test.ts
  types/inferschematype.d.ts
Labels: typescript

#14543 perf(document): add fast path for applying non-nested virtuals to JSON
  lib/document.js
Labels: performance

#14542 docs: de-emphasize `InferSchemaType<>` in TypeScript docs in favor of automatic inference
  docs/typescript/schemas.md
  docs/typescript/subdocuments.md
  docs/typescript/virtuals.md
  types/index.d.ts
Labels: docs
