Repository Automattic/mongoose, pull requests merged in 2024-03, with the labels that each got.

#14328 types: add overwriteMiddlewareResult and skipMiddlewareFunction to types
  package.json
  scripts/tsc-diagnostics-check.js
  test/types/base.test.ts
  test/types/middleware.test.ts
  types/index.d.ts
  types/middlewares.d.ts
Labels: typescript

#14427 Update version support documentation for mongoose 5 & 6
  docs/version-support.md
Labels: docs

#14426 Port #14415 to 7.x
  lib/model.js
Labels: docs

#14423 types(model): make `bulkWrite()` types more flexible to account for casting
  lib/model.js
  lib/query.js
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript

#14422 docs(mongoose): add `options.overwriteModel` details to `mongoose.model()` docs
  lib/index.js
Labels: docs

#14429 Add TypeScript interface for the new PipelineStage - Vector Search - solving issue #14428
  test/types/PipelineStage.test.ts
  types/pipelinestage.d.ts
Labels: typescript

#14430 types: consistently infer array of objects in schema as a DocumentArray
  test/types/docArray.test.ts
  test/types/schema.test.ts
  types/inferschematype.d.ts
Labels: typescript

#14433 Added pre and post function types on Query class
  types/query.d.ts
Labels: typescript

#14434 Add function `SchemaType.prototype.validateAll`
  lib/schemaType.js
  test/schematype.test.js
  types/schematypes.d.ts
Labels: new feature

#14463 fix(types/query): bring "getFilter" and "getQuery" in-line with "find" and other types
  types/query.d.ts
  types/schemaoptions.d.ts
Labels: typescript

#14461 Removed unused hook from docs
  docs/middleware.md
Labels: docs
