Repository Automattic/mongoose, pull requests merged in 2024-07, with the labels that each got.

#14720 types: correct `this` for `validate.validator` schematype option
  test/types/schema.test.ts
  types/schematypes.d.ts
  types/validation.d.ts
Labels: typescript

#14723 docs(model): note that `insertMany()` with `lean` skips applying defaults
  lib/model.js
Labels: docs

#14730 Update some dev-dependencies
  package.json
Labels: dependencies

#14734 types: avoid automatically inferring lean result type when assigning to explicitly typed variable
  test/types/document.test.ts
  test/types/plugin.test.ts
  test/types/queries.test.ts
  types/query.d.ts
Labels: typescript

#14735 types: make `_id` required on Document type
  test/types/docArray.test.ts
  test/types/schema.test.ts
  types/document.d.ts
Labels: typescript

#14737 types(query): fix usage of "RawDocType" where "DocType" should be passed
  types/query.d.ts
Labels: typescript

#14746 Upgrade `mongodb-memory-server` to 10.x
  .github/workflows/test.yml
  .github/workflows/tsd.yml
  package.json
Labels: dependencies
