Repository Automattic/mongoose, pull requests merged in 2025-01, with the labels that each got.

#15159 docs: fix <code> in header ids
  scripts/website.js
Labels: docs

#15160 types: avoid BufferToBinary<> wiping lean types when passed to generic functions
  test/types/lean.test.ts
  types/index.d.ts
  types/query.d.ts
Labels: typescript

#15165 Set ESLint ECMAScript version to `2022`
  .eslintrc.js
Labels: developer-experience

#15184 Schema.prototype.jsonSchema(): convert Mongoose Schema to JSON schema
  lib/helpers/createJSONSchemaTypeDefinition.js
  lib/schema.js
  lib/schema/array.js
  lib/schema/bigint.js
  lib/schema/boolean.js
  lib/schema/buffer.js
  lib/schema/date.js
  lib/schema/decimal128.js
  lib/schema/documentArray.js
  lib/schema/double.js
  lib/schema/int32.js
  lib/schema/map.js
  lib/schema/number.js
  lib/schema/objectId.js
  lib/schema/string.js
  lib/schema/subdocument.js
  lib/schema/uuid.js
  lib/schemaType.js
  package.json
  test/schema.test.js
  types/index.d.ts
  types/schematypes.d.ts
Labels: new feature
