Repository Automattic/mongoose, pull requests merged in 2025-03, with the labels that each got.

#15272 Update field-level-encryption.md
  docs/field-level-encryption.md
Labels: docs

#15298 BREAKING CHANGE: remove _executionStack, make validate() async function and call Kareem hooks directly vs through wrappers
  lib/browser.js
  lib/browserDocument.js
  lib/document.js
  lib/error/validation.js
  lib/helpers/model/applyHooks.js
  lib/query.js
  lib/schema/documentArray.js
  lib/schemaType.js
  test/document.test.js
  test/query.test.js
  test/types.document.test.js
Labels: backwards-breaking

#15303 types(aggregate): add $firstN, $lastN, $bottom, $bottomN, $minN and $maxN operators
  scripts/tsc-diagnostics-check.js
  test/types/PipelineStage.test.ts
  test/types/expressions.test.ts
  types/expressions.d.ts
Labels: typescript

#15304 types(aggregate): allow calling project() with a string
  test/types/aggregate.test.ts
  types/aggregate.d.ts
Labels: typescript

#15328 types: allow default function returning undefined with DocType override
  test/types/schema.test.ts
  types/schematypes.d.ts
Labels: typescript
