Repository Automattic/mongoose, pull requests merged in 2025-05, with the labels that each got.

#15379 Reduce print length in `website.js` and dont exit early in `generateSearch`
  scripts/generateSearch.js
  scripts/website.js
Labels: docs

#15405 docs+types(schema): add alternative optimisticConcurrency syntaxes to docs + types
  lib/schema.js
  types/schemaoptions.d.ts
Labels: docs, typescript

#15413 types(schema): allow post('init')
  test/types/schema.test.ts
  types/index.d.ts
Labels: typescript

#15422 BREAKING CHANGE: make FilterQuery properties no longer resolve to `any` in TypeScript
  docs/migrating_to_9.md
  test/query.test.js
  test/types/queries.test.ts
  types/query.d.ts
Labels: backwards-breaking, typescript

#15418 types: stricter projection typing with 1-level deep nesting
  test/types/models.test.ts
  test/types/queries.test.ts
  types/index.d.ts
  types/query.d.ts
  types/types.d.ts
  types/utility.d.ts
Labels: typescript

#15432 types: correct handling of `_id` in ProjectionType
  test/types/queries.test.ts
  types/index.d.ts
Labels: typescript

#15443 types(model): use ProjectionType for Model.hydrate()
  test/types/models.test.ts
  types/models.d.ts
Labels: typescript
